version: 1.0.0-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_branch_with_pr: true
image:
- Ubuntu1604
- Visual Studio 2017
environment:
  ApiKey:
    secure: F+Q6kHqg+DlND/2yeIt5bXJC5GJ0ZRufxxdwQRkcPT8=
  Timeout: 10
  LinuxJob: 'Image Ubuntu1604'
install:
- sh: sudo apt-get install libtool-bin
build_script:
- sh: |
    set -e
    ./reconf
    ./configure SMTMODEL_H="SmtModelLegacy.h"
    make clean
    make
    cp src/.libs/libthot.so.0.0.0 src/libthot.so
    strip --strip-unneeded src/libthot.so
    appveyor PushArtifact src/libthot.so
- ps: |
    if ($env:APPVEYOR_JOB_NAME -ne $env:LinuxJob) {
        write-host "Waiting for job `"$env:LinuxJob`" to complete"

        $headers = @{
            "Authorization" = "Bearer $env:ApiKey"
            "Content-type" = "application/json"
        }

        [datetime]$stop = ([datetime]::Now).AddMinutes($env:Timeout)
        [bool]$success = $false

        while(!$success -and ([datetime]::Now) -lt $stop) {
            $project = Invoke-RestMethod -Uri "https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG" -Headers $headers -Method GET

            $linuxJobJson = $project.build.jobs | where {$_.name -eq $env:LinuxJob}  
            $success = $linuxJobJson.status -eq "success"
            $linuxJobId = $linuxJobJson.jobId;
            if (!$success) {Start-sleep 5}
        }

        if (!$success) {throw "Job `"$env:LinuxJob`" was not finished in $env:Timeout minutes"}
        if (!$linuxJobId) {throw "Unable to get JobId for the job `"$env:LinuxJob`""}
        
        Start-FileDownload https://ci.appveyor.com/api/buildjobs/$linuxJobId/artifacts/libthot.so -FileName src\msvc\linux\x64\libthot.so
        
        msbuild src\msvc\thot.sln /t:Rebuild /p:Configuration=Release /p:Platform=Win32
        msbuild src\msvc\thot.sln /t:Rebuild /p:Configuration=Release /p:Platform=x64
        nuget pack src\msvc\Thot.nuspec -Version $env:APPVEYOR_BUILD_VERSION -Properties Configuration=Release -BasePath src\msvc -OutputDirectory artifacts
    }
test: off
artifacts:
- path: src\msvc\artifacts\*.nupkg